schema_version: 1

context:
  name: patito
  version: 0.8.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/patito-${{ version }}.tar.gz
  sha256: aba7ac6bb640a075e1c22862dd577519a615724db0694ac3ae81a6a3f3993fb1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.7.0
    - polars >=1.10.0
    - typing_extensions
  run_constraints:
    - pandas *
    - pyarrow >=5.0.0
    - Sphinx <7
    - sphinx_rtd_theme *
    - sphinx-autobuild *
    - sphinx-autodoc-typehints *
    - sphinx-toolbox *
    - sphinxcontrib-mermaid *

tests:
  - python:
      imports:
        - patito
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A dataframe modelling library built on top of polars and pydantic.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/JakobGM/patito
  documentation: https://patito.readthedocs.io/

extra:
  recipe-maintainers:
    - thewchan
